services:
  mongo:
    image: mongo:7
    container_name: songs-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: songs-api
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/songs_db
      - CORS_ORIGIN=http://localhost:5173
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: pnpm dev
volumes:
  mongo-data:
